micronaut:
  application:
    name: pokelabx
  http:
    services:
      pokeapi:
        url: https://pokeapi.co
        path: /api/v2

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
flyway:
  locations: classpath:db/fixture, classpath:db/migration