micronaut:
  application:
    name: pokelabx
datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver
    username: test
    password: test
    schema-generate: NONE
    url: jdbc:tc:postgresql:14:///mydatabase
flyway:
  locations:
    - classpath:db/fixture
    - classpath:db/migration
  datasources:
    default:
      enabled: true
