CREATE TABLE pokemon_detail
(
    id         INTEGER      NOT NULL,
    name       VARCHAR(255) NOT NULL,
    height     INTEGER      NOT NULL,
    weight     INTEGER      NOT NULL,
    sprite_url VARCHAR(255) NOT NULL,
    CONSTRAINT pk_pokemon_detail PRIMARY KEY (id)
);

CREATE TABLE type_entry
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pokemon_id INTEGER                                 NOT NULL,
    slot       INTEGER                                 NOT NULL,
    name       VARCHAR(255),
    url        VARCHAR(255),
    CONSTRAINT pk_type_entry PRIMARY KEY (id)
);

ALTER TABLE pokemon_detail
    ADD CONSTRAINT uc_pokemon_detail_name UNIQUE (name);

ALTER TABLE pokemon_detail
    ADD CONSTRAINT uc_pokemon_detail_sprite_url UNIQUE (sprite_url);

ALTER TABLE type_entry
    ADD CONSTRAINT FK_TYPE_ENTRY_ON_POKEMON FOREIGN KEY (pokemon_id) REFERENCES pokemon_detail (id);